### ISSUE TITLE
For 5.20.5 Version ?

### ISSUE THREAD

**Issue by surikat1978** [VD39/videojs-iplayer-skin-1#2]
You can do for version 5.20.5 and for version 7.5.0 also?  Because for the 5th version control block with a very black and non-transparent background.

**Comment by VD39** [comment]
Sorry, I have no plans for creating a theme for those versions mentioned.

**Comment by surikat1978** [comment]
Looks good template! Another icon **X**   to switch speed to add. Player version is now current 7.5.0. It is a pity that does not fit. Thanks for the answer!
